openapi: 3.0.0
info:
  title: "Anagram-service"
  version: "v1.0.0"
  description: Загрузка словарей и выдача анаграм из словаря
  contact:
    name: Valiev-Ismail
    email: valiev.ismail.it@gmail.com

servers:
  - url: http://localhost:8080/
    description: "localhost server"

paths:
  /get:
    get:
      tags:
        - anagram-service
      parameters:
        - in: query
          name: "word"
          schema:
            type: string
            example: foobar
          required: true
          description: Получение анаграмы
      responses: 
        '200':
          description: OK
          content:
            application/json:
              schema:
                type: array
                items:
                  type: string
                  example: "barfoo"
        '404':
          description: Bad Request
        '500':
          description: Internal Server Error
  /load:
    post:
      tags:
        - anagram-service
      description: Загрузка словаря
      requestBody: 
        description: Получение списка курьеров
        required: true
        content:
          application/json:
            schema:
              type: array
              items:
                type: string
                example: barfoo
      responses:
        '200':
          description: SUCCESS LOAD DICTIONARY, TRY GET ANAGRAM =)
          content:
            application/json:
              schema:
                type: array
                items:
                  type: string
                  example: "foobar"
        '400':
          description: Bad Request
        '500':
          description: Internal Server Error
